# Generated by Django 5.0.4 on 2024-08-19 12:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('background_color', models.CharField(default='#007bff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('border_color', models.CharField(default='#007bff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('text_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code.', regex='^#[0-9A-Fa-f]{6}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('details', models.TextField(blank=True, null=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmactivities.activitytype')),
            ],
        ),
    ]
