# Generated by Django 5.0.4 on 2024-09-03 11:44

from django.db import migrations



def setup_initial_data(apps, schema_editor):
    FarmActivityType = apps.get_model("farmactivities", "FarmActivityType")
    harvesting_activity = FarmActivityType(
        name='Harvesting',
        description='Plant harvesting activity',
        background_color='#F5E8C7',
        border_color='#8B4513',
        text_color='#2F4F4F',
    ).save()

    planting_activity = FarmActivityType(
        name='Planting',
        description='Planting activity',
        background_color='#C4E17F',
        border_color='#228B22',
        text_color='#2C5F2D',
    ).save()

    compost_monitoring_activity = FarmActivityType(
        name='Compost Monitoring',
        description='Compost monitoring activity',
        background_color='#FFD700',
        border_color='#8B4513',
        text_color='#4B5320',
    ).save()

    water_trough_monitoring_activity = FarmActivityType(
        name='Water Trough Monitoring',
        description='Water Trough monitoring activity',
        background_color='#ADD8E6',
        border_color='#4682B4',
        text_color='#2F4F4F',
    ).save()

    insecticide_spraying_activity = FarmActivityType(
        name='Insecticide Spraying',
        description='Spraying activity',
        background_color='#FF6347',
        border_color='#8B0000',
        text_color='#FFFFFF',
    ).save()




class Migration(migrations.Migration):

    dependencies = [
        ('farmactivities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(setup_initial_data),
    ]
