# Generated by Django 5.0.4 on 2024-09-20 14:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmOperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('background_color', models.CharField(default='#007bff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('border_color', models.CharField(default='#007bff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('text_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code.', regex='^#[0-9A-Fa-f]{6}$')])),
            ],
        ),
        migrations.CreateModel(
            name='FarmOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('details', models.TextField(blank=True, null=True)),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_operations.farmoperationtype')),
            ],
        ),
        migrations.CreateModel(
            name='FertilizationOperation',
            fields=[
                ('farmoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_operations.farmoperation')),
                ('treated_area', models.IntegerField(blank=True, null=True)),
                ('application_method', models.CharField(blank=True, max_length=255, null=True)),
                ('fertilization_type', models.CharField(blank=True, max_length=255, null=True)),
                ('fertilizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm_management.fertilizer')),
            ],
            bases=('farm_operations.farmoperation',),
        ),
    ]
