# Generated by Django 5.0.4 on 2024-09-03 11:44

from django.db import migrations
from django.conf import settings



def setup_initial_data(apps, schema_editor):
    FarmOperationType = apps.get_model("farm_operations", "FarmOperationType")
    for def_operation_type in settings.DEFAULT_OPERATION_TYPES.values():
        operation = FarmOperationType(
            **def_operation_type,
        ).save()

    # FarmOperationType = apps.get_model("farm_operations", "FarmOperationType")
    # harvesting_operation = FarmOperationType(
    #     name='Harvesting',
    #     description='Plant harvesting operation',
    #     background_color='#F5E8C7',
    #     border_color='#8B4513',
    #     text_color='#2F4F4F',
    # ).save()

    # planting_operation = FarmOperationType(
    #     name='Planting',
    #     description='Planting operation',
    #     background_color='#C4E17F',
    #     border_color='#228B22',
    #     text_color='#2C5F2D',
    # ).save()

    # compost_monitoring_operation = FarmOperationType(
    #     name='Compost Monitoring',
    #     description='Compost monitoring operation',
    #     background_color='#FFD700',
    #     border_color='#8B4513',
    #     text_color='#4B5320',
    # ).save()

    # water_trough_monitoring_operation = FarmOperationType(
    #     name='Water Trough Monitoring',
    #     description='Water Trough monitoring operation',
    #     background_color='#ADD8E6',
    #     border_color='#4682B4',
    #     text_color='#2F4F4F',
    # ).save()

    # insecticide_spraying_operation = FarmOperationType(
    #     name='Insecticide Spraying',
    #     description='Spraying operation',
    #     background_color='#FF6347',
    #     border_color='#8B0000',
    #     text_color='#FFFFFF',
    # ).save()



class Migration(migrations.Migration):

    dependencies = [
        ('farm_operations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(setup_initial_data),
    ]
