# Generated by Django 5.0.4 on 2024-09-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalfertilizer',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
