# Generated by Django 5.0.4 on 2024-10-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0002_alter_historicalfertilizer_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmanimal',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmanimal',
            name='number_of_animals',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='farmparcel',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='farmparcel',
            name='coordinates',
            field=models.CharField(default=0.0, max_length=255),
        ),
        migrations.AddField(
            model_name='farmparcel',
            name='cultivation_type',
            field=models.CharField(choices=[('grapes', 'Grapes'), ('potato', 'Potato'), ('pasture', 'Pasture')], default='grapes', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalfarmanimal',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalfarmanimal',
            name='number_of_animals',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicalfarmparcel',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalfarmparcel',
            name='coordinates',
            field=models.CharField(default=0.0, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalfarmparcel',
            name='cultivation_type',
            field=models.CharField(choices=[('grapes', 'Grapes'), ('potato', 'Potato'), ('pasture', 'Pasture')], default='grapes', max_length=50),
        ),
    ]
