# Generated by Django 5.0.4 on 2024-10-22 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0003_farmanimal_age_farmanimal_number_of_animals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMenuMaster',
            fields=[
                ('id', models.SmallAutoField(db_column='id', db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z0-9()\\s]+$')])),
                ('menu_icon', models.CharField(blank=True, default='list', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-z0-9-]+$')])),
                ('menu_route', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z0-9\\s-]+$')])),
                ('menu_access', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z0-9\\s-]+$')])),
                ('menu_order', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[0-9]+$')])),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent_id', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='farm_management.adminmenumaster')),
            ],
            options={
                'verbose_name': 'Admin Menu',
                'verbose_name_plural': 'Admin Menus',
                'db_table': 'admin_menu_master',
            },
        ),
    ]
