# Generated by Django 5.0.4 on 2025-02-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0003_compostmaterial_historicalcompostmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compostmaterial',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='compostmaterial',
            name='quantity_unit',
        ),
        migrations.RemoveField(
            model_name='historicalcompostmaterial',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='historicalcompostmaterial',
            name='quantity_unit',
        ),
    ]
