# Generated by Django 5.0.4 on 2024-10-22 20:54

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0004_adminmenumaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAdminMenuMaster',
            fields=[
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated At')),
                ('id', models.IntegerField(blank=True, db_column='id', db_index=True, editable=False, verbose_name='ID')),
                ('menu_name', models.CharField(db_index=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z0-9()\\s]+$')])),
                ('menu_icon', models.CharField(blank=True, default='list', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-z0-9-]+$')])),
                ('menu_route', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z0-9\\s-]+$')])),
                ('menu_access', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z0-9\\s-]+$')])),
                ('menu_order', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[0-9]+$')])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_id', models.ForeignKey(blank=True, db_column='parent_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='farm_management.adminmenumaster')),
            ],
            options={
                'verbose_name': 'historical Admin Menu',
                'verbose_name_plural': 'historical Admin Menus',
                'db_table': 'admin_menu_master_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
