# Generated by Django 5.0.4 on 2025-05-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0006_farmanimal_entry_date_farmanimal_leaving_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmparcel',
            name='geo_id',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='Geographic Data ID'),
        ),
        migrations.AlterField(
            model_name='historicalfarmparcel',
            name='geo_id',
            field=models.CharField(blank=True, db_index=True, null=True, verbose_name='Geographic Data ID'),
        ),
    ]
