# Generated by Django 5.0.4 on 2024-10-17 15:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm_management', '0002_alter_historicalfertilizer_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmCalendarActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('background_color', models.CharField(default='#007bff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('border_color', models.CharField(default='#007bff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('text_color', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code.', regex='^#[0-9A-Fa-f]{6}$')])),
            ],
        ),
        migrations.CreateModel(
            name='FarmCalendarActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_activities.farmcalendaractivitytype')),
            ],
        ),
        migrations.CreateModel(
            name='FertilizationOperation',
            fields=[
                ('farmcalendaractivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_activities.farmcalendaractivity')),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_amount_unit', models.CharField(max_length=255)),
                ('application_method', models.CharField(blank=True, max_length=255, null=True)),
                ('fertilizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm_management.fertilizer')),
                ('operated_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management.farmparcel')),
            ],
            bases=('farm_activities.farmcalendaractivity',),
        ),
    ]
