# Generated by Django 5.0.4 on 2025-02-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='value_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
