# Generated by Django 5.0.4 on 2025-02-10 16:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0002_alter_observation_value_unit'),
        ('farm_management', '0004_remove_compostmaterial_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompostOperation',
            fields=[
                ('farmcalendaractivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_activities.farmcalendaractivity')),
                ('compost_pile_id', models.CharField(max_length=355, verbose_name='Operated On Compost Pile')),
            ],
            options={
                'verbose_name': 'Compost Operation',
                'verbose_name_plural': 'Compost Operations',
            },
            bases=('farm_activities.farmcalendaractivity',),
        ),
        migrations.AddField(
            model_name='farmcalendaractivity',
            name='nested_activities',
            field=models.ManyToManyField(blank=True, related_name='parent_activities', to='farm_activities.farmcalendaractivity'),
        ),
        migrations.CreateModel(
            name='AddRawMaterialCompostQuantity',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_amount_unit', models.CharField(max_length=255)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management.compostmaterial')),
            ],
            options={
                'verbose_name': 'Raw Material Quantity for Operation',
                'verbose_name_plural': 'Raw Material Quantities for Operation',
            },
        ),
        migrations.CreateModel(
            name='AddRawMaterialOperation',
            fields=[
                ('farmcalendaractivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_activities.farmcalendaractivity')),
                ('compost_materials', models.ManyToManyField(through='farm_activities.AddRawMaterialCompostQuantity', to='farm_management.compostmaterial')),
            ],
            options={
                'verbose_name': 'Add Raw Material Operation',
                'verbose_name_plural': 'Add Raw Material Operations',
            },
            bases=('farm_activities.farmcalendaractivity',),
        ),
        migrations.AddField(
            model_name='addrawmaterialcompostquantity',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_activities.addrawmaterialoperation'),
        ),
    ]
