# Generated by Django 5.0.4 on 2025-02-14 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0003_compostoperation_and_more'),
        ('farm_management', '0004_remove_compostmaterial_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationoperation',
            name='operated_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm_management.farmparcel'),
        ),
    ]
