# Generated by Django 5.0.4 on 2025-03-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0004_alter_farmcalendaractivity_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='sensor_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Made By Sensor'),
        ),
    ]
