# Generated by Django 5.0.4 on 2025-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0005_observation_sensor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmcalendaractivitytype',
            name='category',
            field=models.CharField(choices=[('activity', 'Activity'), ('observation', 'Observation'), ('alert', 'Alert')], default='activity', max_length=50),
        ),
    ]
