# Generated by Django 5.0.4 on 2025-03-17 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0005_observation_sensor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPKObservationCollection',
            fields=[
                ('farmcalendaractivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_activities.farmcalendaractivity')),
            ],
            options={
                'verbose_name': 'NPK Observation Collection',
                'verbose_name_plural': 'NPK Observation Collections',
            },
            bases=('farm_activities.farmcalendaractivity',),
        ),
        migrations.AddField(
            model_name='observation',
            name='observation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='farm_activities.npkobservationcollection'),
        ),
    ]
