# Generated by Django 5.0.4 on 2025-05-27 14:25

from django.db import migrations


def set_observation_category(apps, schema_editor):
    FarmCalendarActivityType = apps.get_model('farm_activities', 'FarmCalendarActivityType')

    FarmCalendarActivityType.objects.filter(
        name__icontains='observation'
    ).update(category='observation')

class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0006_farmcalendaractivitytype_category'),
    ]

    operations = [
        migrations.RunPython(set_observation_category),
    ]
